_commit: 2141760
_src_path: ../../softwareco-templates/copier/tpl-project-repo
core_owner_handle: '@softwareco'
org_owner_handle: '@softwareco'
owned_owner_handle: '@softwareco'
repo_slug: test-capabilities
