_src_path: /home/tryinget/ai-society/softwareco/copier/tpl-project-repo
company_name: Software Company
company_ontology_ref: <gitlab:org/ontology@v0.1.0>
company_slug: softwareco
core_owner_handle: '@core-owner'
enable_community_pack: false
enable_release_pack: false
enable_software_pack: false
enable_vouch_gate: false
kernel_ontology_ref: <gitlab:org/ontology-kernel@v0.1.0>
language: typescript
location: owned
org_owner_handle: '@org-owners'
project_owner_handle: '@project-owners'
repo_slug: test-capabilities


