_commit: 927e4c2
_src_path: /home/lightningralf/ai-society/softwareco/tpl-owned-repo
core_owner_handle: '@holding-owner'
org_owner_handle: '@software-owner'
owned_owner_handle: '@software-owner'
repo_slug: testers


