stages:
  - validate

rocs:vendored-check:
  stage: validate
  image: ghcr.io/astral-sh/uv:python3.11-bookworm-slim
  rules:
    - when: always
  allow_failure: true
  script:
    - uvx -n --from ./tools/rocs-cli rocs vendored-check --vendored-dir ./tools/rocs-cli

rocs:validate:
  stage: validate
  image: ghcr.io/astral-sh/uv:python3.11-bookworm-slim
  rules:
    - when: always
  allow_failure: true
  script:
    - python --version
    - uv --version
    - uvx --version
    - uvx -n --from ./tools/rocs-cli rocs version
    - uvx -n --from ./tools/rocs-cli rocs build --repo . --resolve-refs
    - uvx -n --from ./tools/rocs-cli rocs validate --repo . --resolve-refs
  artifacts:
    when: always
    paths:
      - ontology/dist/
