export {
  assertKnownSurfExecutionRoute,
  CLI_OPERATION_REGISTRY,
  CLI_ROUTE_MANIFEST,
  executeCliOperation,
  executeDemoOperation,
  executeDoctorOperation,
  executeHealOperation,
  executeQuantumOperation,
  executeSurfExploreOperation,
  executeTestOperation,
  getCliCommandStatus,
  getSurfActionStatus,
  type RouteRecord,
  requireManifestEntry,
  requireRegisteredOperation,
  resolveCliRoute,
  throwUnavailableManifestEntry,
  throwUnsupportedCommand,
} from "./dispatch-core.js";
