import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import yaml from "js-yaml";
import { z } from "zod";
import { TestCapabilitiesConfigSchema } from "../orchestrator.js";
import type {
  InitOperationInput,
  InitOperationResultEnvelope,
  OperationDefinition,
} from "./types.js";

export const InitOperationInputSchema = z.object({
  output: z.string().optional().default("test-capabilities.yaml"),
  target: z.string().optional().default("node"),
  force: z.boolean().optional().default(false),
  print: z.boolean().optional().default(false),
  json: z.boolean().optional().default(false),
});

type NormalizedInitOperationInput = z.output<typeof InitOperationInputSchema>;

function singleQuoteYaml(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function renderInitConfig(target: string): string {
  return [
    "# TEST-CAPABILITIES configuration",
    "# Generated by `test-capabilities init`.",
    "# This template is intentionally zero-external-dependency: it uses cli-tester only.",
    "# Replace targets.cli with a safe command or executable that supports --help.",
    "",
    "version: '2.0'",
    "name: 'CLI Smoke Suite'",
    "",
    "targets:",
    `  cli: ${singleQuoteYaml(target)}`,
    "",
    "agents:",
    "  cli:",
    "    enabled: true",
    "    type: cli-tester",
    "    intensity: normal",
    "",
    "intelligence:",
    "  self_healing: false",
    "  prediction: false",
    "  correlation: true",
    "  collective: false",
    "",
    "quantum:",
    "  enabled: false",
    "",
    "chaos:",
    "  enabled: false",
    "",
  ].join("\n");
}

function validateRenderedConfig(configText: string): void {
  const raw = yaml.load(configText) ?? {};
  TestCapabilitiesConfigSchema.parse(raw);
}

async function runInitOperation(
  normalized: NormalizedInitOperationInput,
): Promise<InitOperationResultEnvelope> {
  const configText = renderInitConfig(normalized.target);
  validateRenderedConfig(configText);

  const outputPath = path.resolve(process.cwd(), normalized.output);
  const exists = fs.existsSync(outputPath);
  if (exists && !normalized.force && !normalized.print) {
    throw new Error(
      `Refusing to overwrite existing config: ${outputPath}. Re-run with --force, choose --output <file>, or use --print.`,
    );
  }

  let written = false;
  if (!normalized.print) {
    fs.mkdirSync(path.dirname(outputPath), { recursive: true });
    fs.writeFileSync(outputPath, configText, "utf8");
    written = true;
  }

  return {
    operationId: "init",
    input: normalized,
    template: "cli-smoke",
    outputPath,
    written,
    configText,
    nextCommands: [
      normalized.print
        ? `test-capabilities init --output ${normalized.output}`
        : `test-capabilities doctor --config ${normalized.output}`,
      `test-capabilities test --config ${normalized.output} --quick`,
      `test-capabilities test --config ${normalized.output} --json`,
    ],
  };
}

export const INIT_OPERATION = {
  id: "init",
  route: { command: "init" },
  description: "Generate a minimal fail-closed test-capabilities.yaml config",
  inputSchema: InitOperationInputSchema,
  execute: runInitOperation,
} satisfies OperationDefinition<NormalizedInitOperationInput, InitOperationResultEnvelope>;

export function executeInitOperation(
  input: InitOperationInput,
): Promise<InitOperationResultEnvelope> {
  return runInitOperation(InitOperationInputSchema.parse(input));
}
