export {
  CLI_OPERATION_REGISTRY,
  CLI_ROUTE_MANIFEST,
  executeCliOperation,
  executeHealOperation,
  executeQuantumOperation,
  executeSurfExploreOperation,
  executeTestOperation,
  getCliCommandStatus,
  getSurfActionStatus,
  resolveCliRoute,
} from "./operations/dispatch.js";
export {
  assertSupportedSurfExploreOptions,
  assertSupportedTestOptions,
  SURF_EXPLORE_OPTION_SUPPORT,
  TEST_OPTION_SUPPORT,
} from "./operations/support.js";
export type {
  CliCommand,
  CliOperationInputUnion,
  CliOperationResult,
  CliRoute,
  CliRouteManifestEntry,
  HealOperationInput,
  HealOperationResultEnvelope,
  OperationDefinition,
  OperationId,
  OperationStatus,
  QuantumOperationInput,
  QuantumOperationResultEnvelope,
  SurfAction,
  SurfExploreOperationInput,
  SurfExploreOperationResultEnvelope,
  TestOperationInput,
  TestOperationResultEnvelope,
  TestOperationSummary,
} from "./operations/types.js";
