export {
  CLI_OPERATION_REGISTRY,
  CLI_ROUTE_MANIFEST,
  executeCliOperation,
  executeDemoOperation,
  executeDoctorOperation,
  executeHealOperation,
  executeInitOperation,
  executeQuantumOperation,
  executeReplacementValidationOperation,
  executeSurfExploreOperation,
  executeSurfPlanOperation,
  executeTestOperation,
  getCliCommandStatus,
  getSurfActionStatus,
  resolveCliRoute,
} from "./operations/dispatch.js";
export {
  assertSupportedSurfApplyOptions,
  assertSupportedSurfExploreOptions,
  assertSupportedSurfPlanOptions,
  assertSupportedTestOptions,
  SURF_EXPLORE_OPTION_SUPPORT,
  TEST_OPTION_SUPPORT,
} from "./operations/support.js";
export type {
  CliCommand,
  CliOperationInputUnion,
  CliOperationResult,
  CliRoute,
  CliRouteManifestEntry,
  CoreUseCaseGuide,
  DemoOperationInput,
  DemoOperationResultEnvelope,
  DoctorCheck,
  DoctorOperationInput,
  DoctorOperationResultEnvelope,
  HealOperationInput,
  HealOperationResultEnvelope,
  HealProposalArtifactRef,
  HealReceiptArtifactRef,
  HealVerificationArtifactRef,
  InitOperationInput,
  InitOperationResultEnvelope,
  OperationDefinition,
  OperationId,
  OperationStatus,
  QuantumOperationInput,
  QuantumOperationResultEnvelope,
  ReplacementValidationOperationInput,
  ReplacementValidationOperationResultEnvelope,
  SurfAction,
  SurfExploreOperationInput,
  SurfExploreOperationResultEnvelope,
  SurfPlanEnvelopeField,
  SurfPlanOperationInput,
  SurfPlanOperationResultEnvelope,
  TestOperationInput,
  TestOperationResultEnvelope,
  TestOperationSummary,
} from "./operations/types.js";
